# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Protactor Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    env:
      LT_USERNAME: gauravkb
      LT_ACCESS_KEY: DqLVVOF1ll4TTMyXXt3gslp8NZ8Ynon3vwcRd4eFTV5GLavGh9
    steps: 
      - uses: actions/checkout@v2      
      - uses: actions/setup-node@v2       
        with:          
          node-version: 12     
      - run: brew install node
      - run: npm install
      - run:
          echo "The LT_USERNAME na"
      - run: npm run single

